Add Java. Include base test examples and a few sample solutions
LeetCube/LeetCube pull request #43
Opened 2023-06-04 18:13 UTC by PhaseRush

I've edited the `run.md` file to add a detailed instructions on how to get the project set up. Seeking comments regarding that.

2023-06-04 18:13 UTC, PhaseRush commented
There are some other things left to do, such as configuring a linter and some small details here and there. But this is a good first effort and I'd like to push it before I lose steam.

2023-06-04 19:17 UTC, dataprob reviewed
Great work Requiem! I'll spend some time going thru the instructions to run

2023-06-04 21:03 UTC, dataprob commented
Figured out how to do this in vscode, I'll add to doc later too.

2023-06-04 21:05 UTC, dataprob commented on doc/run.md
> +1. [Clone the repo via IntelliJ](https://www.jetbrains.com/help/idea/cloning-repository.html). ![cloning in intellij](figs/java/1_1_clone.png)
For all images in markdown, add a new line b4 and after, o.w. you have text and image on same line.
See how I did in GitCube https://github.com/LeetCube/GitCube/blob/main/pr/vsc.md?plain=1

2023-06-04 21:05 UTC, dataprob requested changes
See my comment about images in `run.md`, o.w. all good!

2023-06-05 03:04 UTC, dataprob approved these changes
Awesome!

2023-06-05 03:04 UTC, merged